add_newline = false
format = """
[$line_breakâ”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€(\\[ $git_branch$git_commit$git_state$git_metrics$git_status \\])-â”€â”€â”€â”€â”€â”€â”€â”€â”€(\\[$jobs\\])(\\[$cmd_duration\\])â†’](bold green)
[â”‚](bold green)($username(@$hostname) )$directory$shlvl$kubernetes$vcsh$docker_context$package$cmake$dart$deno$dotnet$elixir$elm$erlang$golang$helm$java$julia$kotlin$nim$nodejs$ocaml$perl$php$purescript$python$red$ruby$rust$scala$swift$terraform$vlang$vagrant$zig$nix_shell$conda$memory_usage$aws$gcloud$openstack$env_var$crystal$custom$lua$battery$time$status$shell
[â””â”€$character](bold green) """

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"

[cmd_duration]
format = "[à³±$duration]($style)"
disabled = false

[directory]
truncation_symbol = "â€¦/"
truncation_length = 8

[git_branch]
format = "[$symbol$branch]($style)"
symbol = "â¸™"

[git_status]
format = '([( $ahead_behind)( $staged)( $renamed)( $modified)( $deleted)( $conflicted)( $untracked)( $stashed)]($style))'
conflicted = "[!$count](red)"
ahead = "[â‡¡$count](green)"
behind = "[â‡£$count](red)"
diverged = "[$ahead_count](green)â†•[behind_count](red)"
untracked = "[?$count](purple)"
stashed = "ğŸ“¦"
modified = "[~$count](yellow)"
staged = '[+$count](green)'
renamed = "[Â»$count](cyan)"
deleted = "[-$count](red)"

[hostname]
disabled = true

[line_break]
disabled = true

[shell]
fish_indicator = "ğŸ¦ˆ"
bash_indicator = "ğŸŒ"
powershell_indicator = "[â¯_](green)"
disabled = true

[time]
disabled = true