# To get it working on docker:
# ----------------------------------------------------
# sh -c "$(curl -fsSL https://starship.rs/install.sh)"; echo '''eval "$(starship init bash)"''' >> ~/.bashrc; mkdir ~/.config; code ~/.config/starship.toml
# ----------------------------------------------------

add_newline = false
format = '''
[$line_breakâ”Œ(\[[$shell]($style)\])$fill(\[ $git_branch$git_commit$git_state$git_metrics$git_status \])$fill(\[$jobs\])(\[$cmd_duration\])â†’](bold green)
[â”‚](bold green)($username(@$hostname) )$directory$shlvl$kubernetes$vcsh$docker_context$package$cmake$dart$deno$dotnet$elixir$elm$erlang$golang$helm$java$julia$kotlin$nim$nodejs$ocaml$perl$php$purescript$python$red$ruby$rust$scala$swift$terraform$vlang$vagrant$zig$nix_shell$conda$memory_usage$aws$gcloud$openstack$env_var$crystal$custom$lua$battery$time$status
[â””â”€$character](bold green) '''

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"

[cmake]
symbol = "â–³"
format = "[$symbol($version)]($style)"

[cmd_duration]
format = "[à³±$duration]($style)"
disabled = false

[directory]
truncation_symbol = "â€¦/"
truncation_length = 8

[fill]
symbol = "â”€"
style = "bold green"

[git_branch]
format = "[$symbol $branch]($style)"
symbol = "î‚ "

[git_status]
format = '([( $ahead_behind)( $staged)( $renamed)( $modified)( $deleted)( $conflicted)( $untracked)( $stashed)]($style))'
conflicted = "[!$count](red)"
ahead = "[â‡¡$count](green)"
behind = "[â‡£$count](red)"
diverged = "[$ahead_count](green)â†•[$behind_count](red)"
untracked = "[?$count](purple)"
stashed = "ğŸ“¦"
modified = "[~$count](yellow)"
staged = '[+$count](green)'
renamed = "[Â»$count](cyan)"
deleted = "[-$count](red)"

[hostname]
format = "[($hostname)]($style)"
disabled = false

[line_break]
disabled = true

[nodejs]
symbol = "à¨¹"
format = "[($symbol$version)]($style)"

[package]
symbol = "ğŸ“¦"
format = "[$symbol$version]($style)"

[php]
symbol = "ğŸ˜"
format = "[$symbol$version]($style)"

[python]
symbol = "ğŸ"
format = "[${symbol}${pyenv_prefix}(${version})(-\\($virtualenv\\))]($style)"

[shell]
format = "[$indicator]($style)"
fish_indicator = "ğŸ¦ˆ"
bash_indicator = "ğŸŒ"
powershell_indicator = "[â¯_](green)"
disabled = false

[time]
disabled = true
